[project]
name = "llrp-interface"
version = "0.1.0"
description = "Web based llrp interface"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "pydantic>=2.10.6",
    "sllurp>=2.0.1",
    "uvicorn>=0.34.0",
    "websockets>=15.0",
]
